export enum AppConstant {
  LOGIN_URL = "/wp-json/jwt-auth/v1/token",
  REGISTER_URL = "/wp-json/wp/v2/users",
  USER_URL = "/wp-json/wp/v2/users",
  TOKEN_VALIDATION_URL = "/wp-json/jwt-auth/v1/token/validate",
  BASE_WP_URL = "https://panalearn.com/tutor-v1",
  ADMIN_TOKEN_KEY = "ADMIN_TOKEN",
  USER_TOKEN_KEY = "USER_TOKEN",
  SERVER_SUB_DIR = "/dev/api",
  COURSE_CATEGORIES_URL = "/wp-json/wp/v2/course_categories",
  COURSES_URL = "/wp-json/wp/v2/courses",
  COURSE_CHAPTERS_URL = "/wp-json/wp/v2/course_chapters",
  COURSE_LESSONS_URL = "/wp-json/wp/v2/course_lessons",
  QUIZZES_URL = "/wp-json/wp/v2/quiz",
  QUIZ_QUESTIONS_URL = "/wp-json/wp/v2/question_box",
  MEDIA_URL = "/wp-json/wp/v2/media",
}
